mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Home page for the site.
    url(r'^$', 'todo.views.home', name='home'),
    # About page for the site.
    url(r'^about$', 'todo.views.about', name='about'),
    # registration page for the site.
    url(r'^register', 'views.register', name='register'),
    # registration page for the site.
    url(r'^accounts/profile', 'todo.views.home', name='profile'),
    # login page for the site.
    url(r'^accounts/login', 'django.contrib.auth.views.login', name='login'),
    # logout page for the site. # {'next_page': '/accounts/login/?next=/'}
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    # admin module provided by django.
    url(r'^admin/', include(admin.site.urls)),
    # Todo app created on my own for learning purpose.
    url(r'^todo/', include('todo.urls', namespace="todo")),
    # Custom login attempt for Todo app.
    url(r'^login/', 'todo.views.login_request', name='login_request'),

]

todo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.todolist, name='index'),
    url(r'^quickdetail_todo/$', views.quickdetail_todo, name='quickdetail_todo'),
    url(r'^edit_todo/$', views.edit_todo, name='edit_todo'),
    url(r'^quickedit_todo/$', views.quickedit_todo, name='quickedit_todo'),
    url(r'^quickadd_todo/$', views.quickadd_todo, name='quickadd_todo'),
    url(r'^add_todo/$', views.add_todo, name='add_todo'),
    url(r'^quickdelete_todo/$', views.quickdelete_todo, name='quickdelete_todo'),

    url(r'^reports/todo_reports/$', views.todo_reports, name='todo_reports'),
    url(r'^todo_reports/$', views.todo_reports, name='todo_reports'),
    url(r'^reports/$', views.reports, name='reports'),

    url(r'^mark_as_completed/$', views.mark_as_completed, name='mark_as_completed'),
    url(r'^unmark_as_completed/$', views.unmark_as_completed, name='unmark_as_completed'),
    url(r'^search/$', views.todo_search, name='todo_search'),
    url(r'^completed_todo_list/$', views.completed_todolist, name='completed_todo_list'),
    url(r'^deleted_todo_list/$', views.deleted_todolist, name='deleted_todo_list'),

    # Test url to test UI stuff.
    url(r'^tabs', views.todo_tab_test, name='todo_tab_test'),
]

todo/forms.py
from django import forms
from todo.models import Todo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class TodoForm(forms.ModelForm):

    name = forms.CharField(max_length=200, help_text="Please enter the Todo name.")
    description = forms.CharField(max_length=400, required=False, help_text="Optional Todo description..")
    priority = forms.CharField(max_length=8, help_text="Please enter the Todo priority.")
    notes = forms.CharField(max_length=300, required=False, help_text="Optional Todo notes.")
    tags = forms.CharField(max_length=100, required=False, help_text="Optional Todo tags.")
    project = forms.CharField(max_length=200, required=False, help_text="Optional Todo project.")
    email = forms.CharField(max_length=100, required=False, help_text="Optional Todo email.")
    phone_number = forms.CharField(max_length=12, required=False, help_text="Optional Todo phone number.")
    address = forms.CharField(max_length=200, required=False, help_text="Optional Todo address.")

    class Meta:
        model = Todo
        # exclude = ['author', 'updated', 'created', ]
        fields = ['name', 'description', 'priority', 'notes', 'tags', 'project', 'email', 'phone_number', 'address']

        widgets = {
            'name': forms.TextInput(
                attrs={'id': 'post-text', 'required': True, 'placeholder': 'Say something...'}
            ),
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required = True)
    last_name = forms.CharField(required = True)

    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

todo/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.core import serializers
from datetime import datetime, time
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.context_processors import csrf
from django.db.models import Count

from todo.forms import RegistrationForm, TodoForm


import json
import re

from .models import Todo

# Create your views here.

@login_required(login_url='/login/')
def todolist(request):
    'list view of the todo app.'
    todo_list = Todo.objects.filter(user=request.user.id).filter(iscompleted=False).filter(isdeleted=False).order_by('-created_date')
    prioritylist = Todo.PRIORITY_LIST

    context = {
        'latest_todo_list': todo_list,
        'prioritylist': prioritylist,
    }
    return render(request, 'todo/index.html', context)

@login_required
def edit_todo(request):
    'detailed view of a individual todo.'
    if request.method == 'POST':

        todoid = request.POST.get('todoid')
        todoname = request.POST.get('todoname')
        todopriority = request.POST.get('todopriority')
        tododescription = request.POST.get('tododescription')
        todonotes = request.POST.get('todonotes')
        todotags = request.POST.get('todotags')
        todoproject = request.POST.get('todoproject')
        todoemail = request.POST.get('todoemail')
        todophone = request.POST.get('todophone')
        todoaddress = request.POST.get('todoaddress')
        todouser = request.user.id

        updatedtodo = Todo(id=todoid, name=todoname, description=tododescription,
                 priority=todopriority, notes=todonotes, tags=todotags,
                 project=todoproject, email=todoemail, phone_number=todophone,
                 address=todoaddress, user_id=todouser)
        print updatedtodo
        updatedtodo.save()

        response_data = dict()
        todo = Todo.objects.filter(user=todouser).get(pk=todoid)
        todoname = todo.name
        todopriority = todo.priority

        tododescription = todo.description
        todonotes = todo.notes
        todotags = todo.tags
        todoproject = todo.project
        todoemail = todo.email
        todophone_number = todo.phone_number
        todoaddress = todo.address

        response_data['todoid'] = todoid
        response_data['todoname'] = todoname
        response_data['todopriority'] = todopriority
        response_data['todouser'] = todouser
        response_data['tododescription'] = tododescription
        response_data['todonotes'] = todonotes
        response_data['todotags'] = todotags
        response_data['todoproject'] = todoproject
        response_data['todoemail'] = todoemail
        # Phone number Model field(phone_number) & View parameter(phone) are different
        response_data['todophone'] = todophone_number
        response_data['todoaddress'] = todoaddress

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )

    else:
        return HttpResponse(
            json.dumps({"No Data": "Are you kidding me !! :)"}),
            content_type="application/json"
        )

@login_required
def quickdetail_todo(request):
    'detailed view of a individual todo.'
    if request.method == 'POST':

        todoid = request.POST.get('todoid')
        todouser = request.user.id
        response_data = dict()
        todo = Todo.objects.filter(user=todouser).get(pk=todoid)
        todoname = todo.name
        todopriority = todo.priority

        tododescription = todo.description
        todonotes = todo.notes
        todotags = todo.tags
        todoproject = todo.project
        todoemail = todo.email
        todophone_number = todo.phone_number
        todoaddress = todo.address

        response_data['todoid'] = todoid
        response_data['todoname'] = todoname
        response_data['todopriority'] = todopriority
        response_data['todouser'] = todouser
        response_data['tododescription'] = tododescription
        response_data['todonotes'] = todonotes
        response_data['todotags'] = todotags
        response_data['todoproject'] = todoproject
        response_data['todoemail'] = todoemail
        response_data['todophone_number'] = todophone_number
        response_data['todoaddress'] = todoaddress

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )

    else:
        return HttpResponse(
            json.dumps({"No Data": "Are you kidding me !! :)"}),
            content_type="application/json"
        )

@login_required
def quickedit_todo(request):
    'edit a individual todo.'
    if request.method == 'POST':
        todoid = request.POST.get('todoid')
        todoname = request.POST.get('todoname')
        todopriority = request.POST.get('todopriority')
        todoreminderdate = request.POST.get('todoreminderdate')
        todouser = request.user.id
        response_data = dict()
        if todoreminderdate:
            todoreminderdate = datetime.strptime(todoreminderdate, '%m/%d/%y %H:%M')
            # todoreminderdate = datetime.combine(todoreminderdate, time.min)
            t = Todo(id=todoid, name=todoname, priority=todopriority,
                 user_id=todouser, reminder_date=todoreminderdate)
            t.save()
            response_data['result'] = 'Update Todo successful!'
            response_data['todoid'] = t.pk
            response_data['todoname'] = t.name
            response_data['todopriority'] = t.priority
            response_data['todoreminderdate'] = str(t.reminder_date.strftime('%m/%d/%y %H:%M'))
        else:
            t = Todo(id=todoid, name=todoname, priority=todopriority,
                 user_id=todouser)
            t.save()
            response_data['result'] = 'Update Todo successful!'
            response_data['todoid'] = t.pk
            response_data['todoname'] = t.name
            response_data['todopriority'] = t.priority
        print t

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"No Data": "Are you kidding me !! :)"}),
            content_type="application/json"
        )


@login_required
def quickadd_todo(request):
    'add an individual todo.'
    if request.method == 'POST':
        todoname = request.POST.get('todoname')
        todopriority = request.POST.get('todopriority')
        todo_reminder_date = request.POST.get('todoreminder_date')
        todouser = request.user.id
        response_data = dict()
        if todo_reminder_date:
            todo_reminder_date = datetime.strptime(todo_reminder_date, '%m/%d/%y %H:%M')
            t = Todo(name=todoname, priority=todopriority, user_id=todouser, reminder_date=todo_reminder_date)
            t.save()
            response_data['result'] = 'Update Todo successful!'
            response_data['todoid'] = t.pk
            response_data['todoname'] = t.name
            response_data['todopriority'] = t.priority
            response_data['todoreminderdate'] = str(t .reminder_date.strftime('%m/%d/%y %H:%M'))
        else:
            t = Todo(name=todoname, priority=todopriority, user_id=todouser)
            t.save()
            response_data['result'] = 'Update Todo successful!'
            response_data['todoid'] = t.pk
            response_data['todoname'] = t.name
            response_data['todopriority'] = t.priority

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"No Data": "Are you kidding me !! :)"}),
            content_type="application/json"
        )


@login_required
def add_todo(request):
    'add an individual todo.'
    if request.method == 'POST':
        todoname = request.POST.get('todoname')
        todopriority = request.POST.get('todopriority')
        tododescription = request.POST.get('tododescription')
        todouser = request.user.id
        todonotes = request.POST.get('todonotes')
        todotags = request.POST.get('todotags')
        todoproject = request.POST.get('todoproject')
        todoemail = request.POST.get('todoemail')
        todophonenumber = request.POST.get('todophonenumber')
        todoaddress = request.POST.get('todoaddress')
        response_data = dict()

        t = Todo(name=todoname, priority=todopriority, user_id=todouser, description=tododescription,
                 notes=todonotes, tags=todotags, project=todoproject, email=todoemail,
                 phone_number=todophonenumber, address=todoaddress)
        t.save()

        response_data['result'] = 'Update Todo successful!'
        response_data['todoid'] = t.pk
        response_data['todoname'] = t.name
        response_data['todopriority'] = t.priority
        response_data['tododescription'] = t.description
        response_data['todonotes'] = t.notes
        response_data['todotags'] = t.tags
        response_data['todoproject'] = t.project
        response_data['todoemail'] = t.email
        response_data['todophonenumber'] = t.phone_number
        response_data['todoaddress'] = t.address

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"No Data": "Are you kidding me !! :)"}),
            content_type="application/json"
        )


@login_required
def mark_as_completed(request):
    'Mark a todo as Completed.'

todo/templates/todo/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="images/favicon.ico">

    <title>Django Practice Apps Home Page</title>

    {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'todo/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/todo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/datepicker.min.css' %}" rel="stylesheet" />

    <!-- Javscript constants -->
    <script type="text/javascript" src="{% static 'todo/js/todo-constants.js' %}"></script>


</head>
<body >
    {% if user.is_authenticated %}
        {% include "todo/header.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/header.html" %}
    {% endif %}

    <div class="container">
        <div class="row">
            {% if user.is_authenticated %}
                {% include "todo/sidebar.html" with isAuthenticated="True"%}
            {% else %}
                {% include "todo/sidebar.html" %}
            {% endif %}
            <div class="col-sm-9 col-md-10 custom-main">

                <!--<h4 class="sub-header" id="header-todo-search"> Search Results</h4>-->
                <div class="row placeholders" id="div-about-content" >

                    {% if user.is_authenticated %}
                        <h4><a href="{% url 'todo:index' %}"> Todo-task </a></h4>
                    {% else %}
                        <!--<h4><a href="{% url 'login' %}"> Todo </a></h4>-->
                        <h4><a href="{% url 'todo:index' %}"> Todo-task </a></h4>
                    {% endif %}

                    <p>This is a app to organise your todo's / reminders / tasks all in one place.
                        We'll be adding more features to the todo-task app by including third party api's (Evernote, GIT, googledocs etc).
                        Todo-task app's basic features are add, edit, delete, mark as completed Todo's. We will be adding more features as we keep developing.
                        <ul>
                            <li> The Todo's are user specific and you can add Tags, Projects and prioritise Todo's. </li>
                            <li> Todo's can be shared to users. </li>
                            <li> Group the tasks related to a project.</li>
                            <li> Create sub-task's to drill down complex tasks.</li>
                        </ul>

                    </p>

                </div>

            </div>
        </div>
    </div>



    <!-- Loading Footer , Javascript / Jquery files -->

    {% if user.is_authenticated %}
        {% include "todo/footer.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/footer.html" %}
    {% endif %}

    <!-- Loading Javascript specific to page -->


</body>
</html>

todo/templates/todo/footer-includes.html
{% load staticfiles %}


<script type="text/javascript" src="{% static 'todo/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/jquery-1.11.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/todo.js' %}"></script>

<script type="text/javascript" src="{% static 'todo/js/bootstrap-datepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'todo/js/en-gb.js' %}"></script>


<script type="text/javascript" src="{% static 'todo/js/todo-utilities.js' %}"></script>

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="{% static 'todo/js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
<script src="{% static 'todo/js/ie-emulation-modes-warning.js' %}"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

todo/templates/todo/footer.html
{% load staticfiles %}

<footer class="footer">
    <div class="container">

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" >

        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="text-align: center;">
            &copy; {% now "Y" %} <a href="{% url 'home' %}"> todo-task.com </a>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" >

        </div>
    </div>
</footer>

todo/templates/todo/header.html
<!-- Google Analytics  -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66885216-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Todo-task</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="active"><a href="{% url 'todo:index' %}">Todo</a></li>
                    <li><a href="#" onclick="showReportTodo()" id="scrollTo">Reports</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                {% else %}
                    <!--<h4><a href="{% url 'login' %}"> Todo </a></h4>-->
                    <li class="active"><a href="{% url 'todo:index' %}">Todo</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                {% endif %}

            </ul>
            {%if isAuthenticated == "True" %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
            {%else%}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!--<a href="{% url 'login' %}">login</a>-->
                        <a href="{% url 'login_request' %}"> Login  </a>
                    </li>
                   <li> <a href="{% url 'register' %}" >Register</a></li>
                </ul>
            {% endif %}
        </div><!--/.nav-collapse -->

    </div>
</nav>

todo/templates/todo/home.html
 {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'todo/images/favicon.ico' %} ">
    <title>Todo-task : Home Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'todo/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/todo.css' %}" />

    <!-- Javascript constants -->
    <script type="text/javascript" src="{% static 'todo/js/todo-constants.js' %}"></script>

</head>
<body id="body-home-pg">
    {% if user.is_authenticated %}
        {% include "todo/header.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/header.html" %}
    {% endif %}
    <!--
        This is the Homepage for the whole project. It is home to multiple projects.
        Please do not delete it or be sure about the changes if you do so.
    -->

    <div class="container">
        <div class="col-lg-12">
            {% if user.is_authenticated %}
                <h4><a href="{% url 'todo:index' %}"> Todo-task </a></h4>
            {% else %}
                <!--<h4><a href="{% url 'login' %}"> Todo </a></h4>-->
                <h4><a href="{% url 'todo:index' %}"> Todo-task </a></h4>
            {% endif %}

            <p>This is a app to organise your todo's / reminders / tasks all in one place.
                We'll be adding more features to the todo-task app by including third party api's (Evernote, GIT, googledocs etc).
                Todo-task app's basic features are add, edit, delete, mark as completed Todo's. We will be adding more features as we keep developing.
                <ul>
                    <li> The Todo's are user specific and you can add Tags, Projects and prioritise Todo's. </li>
                    <li> Todo's can be shared to users. </li>
                    <li> Group the tasks related to a project.</li>
                    <li> Create sub-task's to drill down complex tasks.</li>
                </ul>

            </p>
            <!--<h4><a href="{% url 'login_request' %}"> login Test </a></h4>-->


        </div>

    </div>


    <!-- Loading Footer, Javascript / Jquery files -->

    {% if user.is_authenticated %}
    {% include "todo/footer.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/footer.html" %}
    {% endif %}

</body>
</html>

todo/templates/todo/reports.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="images/favicon.ico">

    <title>Django Practice Apps Home Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'todo/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'todo/css/dashboard.css' %}" />-->
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/todo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'todo/css/datepicker.min.css' %}" rel="stylesheet" />


     <!-- Javascript Constants -->
    <script type="text/javascript" src="{% static 'todo/js/todo-constants.js' %}"></script>


</head>
<body >
    {% if user.is_authenticated %}
        {% include "todo/header.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/header.html" %}
    {% endif %}

    <div class="container">
        <div class="row">
            {% if user.is_authenticated %}
                {% include "todo/sidebar.html" with isAuthenticated="True"%}
            {% else %}
                {% include "todo/sidebar.html" %}
            {% endif %}

            <div class="col-sm-9 col-md-10 custom-main">

                <div class="input-group" id="search-box-container" style="display: inline-table; width: 80%; margin-top: 30px; margin-bottom: 10px;">
                  <span class="input-group-btn">
                    <button class="btn btn-default" id="search-button" type="button">Go!</button>
                  </span>
                  <input type="text" id="search-box" class="form-control" placeholder="Search for...">
                </div>
                <!-- /search-box-group -->
                <div style="display: inline; width: 20%;" >
                    <a href="#" id="link-show-add"  >
                        <img id="img-add-todo" src="{% static 'todo/images/plus_sign.png' %}" title="Add Todo"/>
                    </a>
                </div>


                <div class="form-group">
                    <div id="startDateLabel" > Start : </div>
                    <div class='input-group date' id='div-startdate'>
                        <input type='text' class="form-control" name="div-startdate" id="input-div-startdate" />
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <div id="endDateLabel" > End : </div>
                    <div class='input-group date' id='div-enddate'>
                        <input type='text' class="form-control" name="div-enddate" id="input-div-enddate" />
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <div class="" id='getReport'>
                        <input type='button' class="btn btn-primary btn-md" name="getReport" value="Report" />
                    </div>

                </div>

                <div id="reportByPriority" class="panel-body" style=""></div>
                <div id="results">

                </div>


            </div>



        </div>
    </div>




    <!-- Loading Footer, Javascript / Jquery files -->

    {% if user.is_authenticated %}
    {% include "todo/footer.html" with isAuthenticated="True"%}
    {% else %}
        {% include "todo/footer.html" %}
    {% endif %}

    <!-- Loading Javascript specific to reports html -->
    <script type="text/javascript" src="{% static 'todo/js/highcharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'todo/js/exporting.js' %}"></script>
    <script type="text/javascript" src="{% static 'todo/js/reports.js' %}"></script>


</body>
</html>

todo/templates/todo/sidebar.html
<div class="col-sm-3 col-md-2 custom-sidebar">
    <ul class="nav nav-sidebar">
        <li class="active"><a href="{% url 'todo:index'  %}">Todo's <span class="sr-only">(current)</span></a></li>
        <li><a href="#" onclick="showReportTodo()" id="scrollTo">Reports</a></li>
        <li><a href="#" onclick="showProjectTodo()" >Projects</a></li>
        <li><a href="#">Tags</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#" id="scrollTop">Back to Top</a></li>
    </ul>
</div>